# Generated by Django 5.1.2 on 2024-10-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='make',
            new_name='marca',
        ),
    ]
