# Generated by Django 5.1.2 on 2024-10-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_remove_driver_vehicle_vehicle_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
